Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.define "wordpress" do |w|
    w.vm.network "public_network", ip: "192.168.100.126"

    w.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "wordpress"
    end

  end

  config.vm.define "mysql" do |mysql|
    mysql.vm.network "public_network", ip: "192.168.100.127"

    mysql.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "mysql"
    end

  end

  
end
